### PR TITLE
content updates

### PR DESCRIPTION
**Pull request by KentHall2018**
issue for reference: https://github.ibm.com/Bluemix/docs/issues/10714

### Description

first round of content updates

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by alex-reiff** [comment]
image

Does this page also needs its capitalization updated?

**Comment by KentHall2018** [comment]
@alex-reiff I don't see anything in that screenshot that would need updated. "VPC" should stay capitalized, if that's what you're asking about. and since we do sentence style, "Management" and "Workload" are fine how they are. same goes for "Create" and "About"

**Comment by alex-reiff** [comment]
@KentHall2018 The other VPS pages look like this: 
image

Should it be consistent across all 3?

---

Also the unit tests are going to fail because they check the old strings. If you're done making changes I will go in and fix them.

**Comment by KentHall2018** [comment]
@alex-reiff good catch. those should probably be capitalized. 

and yeah I'm done making updates for now

**Review by alex-reiff — APPROVED** [review]

**Pull request merged**
