### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by alex-reiff**
### Description

Changes as detailed here: https://github.ibm.com/GoldenEye/issues/issues/7177#issuecomment-79579809

Still need to update the URLs that are linked throughout in tooltips.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by alex-reiff** [comment]
also fixes https://github.ibm.com/GoldenEye/issues/issues/9177 introduced in the last doc PR

**Review by akocbek — APPROVED** [review]

**Pull request merged**
